# redis.conf
bind 0.0.0.0  # Разрешить подключение из всех источников
protected-mode yes
port 6379

maxmemory 512mb
maxmemory-policy allkeys-lru  # Политика удаления ключей

save 900 1  # Снимок каждые 15 минут при наличии хотя бы 1 изменения
save 300 10  # Снимок каждые 5 минут при наличии хотя бы 10 изменений
appendonly yes  # Включить журналирование (AOF)
appendfsync everysec  # Синхронизация каждую секунду
